using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class Introcutscene : MonoBehaviour
{
    public RectTransform myImage;   // drag your UI Image here in Inspector
    public Vector2 targetPosition = new Vector2(-220f, -400f);
    public float speed = 5f;

    public AudioSource audioSource;
    public AudioClip footsteps;
    public AudioClip speaking;
    public AudioClip growl;
    public AudioClip gruntSmall;
    public AudioClip sigh;
    public AudioClip clearThraot;
    public AudioClip anger;
    bool enteredScene = false;
    public RectTransform speechBobble; 
    public GameObject speechThingy; 
    public TMPro.TextMeshProUGUI speechText;
    public Button next; 
    private int Step = 0;

    public GameObject blip1;
    public GameObject blip2;
    public GameObject blip3;
    public GameObject blip4;
    public GameObject blip5;
    public RectTransform book;

    void Start()
    {
        next.onClick.AddListener(NextStep);
    }
    void Update()
    {
        if (enteredScene == false)
        {
           if (Vector2.Distance(myImage.anchoredPosition, targetPosition) > 0.1f)
            {
                if (!audioSource.isPlaying) 
                {
                    audioSource.clip = footsteps;
                    audioSource.loop = true;
                    audioSource.Play();
                }
                myImage.anchoredPosition = Vector2.MoveTowards(
                myImage.anchoredPosition,
                targetPosition,
                speed * Time.deltaTime
            );
            } 
            else
            {
            enteredScene = true;

            audioSource.Stop(); 
            audioSource.PlayOneShot(speaking);
            ShowSpeech("At ease, Soldier!", 56f, 165);
            speechThingy.SetActive(true);
            next.gameObject.SetActive(true);
            }
        }
        
    }

    public void ShowSpeech(string text, float xPos, float yPos)
{
    speechText.text = text;
    speechBobble.gameObject.SetActive(true);
    LayoutRebuilder.ForceRebuildLayoutImmediate(speechBobble);
    speechBobble.anchoredPosition = new Vector2(xPos, yPos);
}

    void NextStep()
    {
        Step++;

        if (Step == 1)
        {
            audioSource.PlayOneShot(gruntSmall);
            ShowSpeech("You’re our new communications expert? A little young, aren’t we?", 56f, 275f);
        }
        else if (Step == 2)
        {
            myImage.localScale = new Vector3(1.4f, 1.4f, 1f);
            audioSource.PlayOneShot(growl);
            ShowSpeech("Hm. What was that? You think you have what it takes to protect your fellow soldiers?", 56f, 325f);
        }
        else if (Step == 3)
        {
            myImage.localScale = new Vector3(1.1f, 1.1f, 1f);
            ShowSpeech("Well, I guess we better get you introduced to the work then.", 56f, 275f);
        }
        else if (Step == 4)
        {
            audioSource.PlayOneShot(gruntSmall);
            ShowSpeech("The enemy has managed to infiltrate our systems, using their brand new <b>LLM-</b>", 56f, 320f);
        }
        else if (Step == 5)
        {
            audioSource.PlayOneShot(sigh);
            ShowSpeech("You don’t know what an <b>LLM</b> is? A <b>large language model</b>. It’s an <b>AI</b>.", 56f, 330f);
        }
        else if (Step == 6)
        {
            audioSource.PlayOneShot(clearThraot);
            ShowSpeech("Anyways, your job is to figure out what information is generated by their <b>AI model</b>.", 56f, 330f);
        }
        else if (Step == 7)
        {
            blip1.SetActive(true);
            ShowSpeech("This is a blip, indicating the enemies position. Each of these has information attached that allows our soldiers in the field to track them.", 56f, 425f);
        }
        else if (Step == 8)
        {
            audioSource.PlayOneShot(anger);
            ShowSpeech("If the wrong information is let through to our team…", 56f, 225f);
        }
        else if (Step == 9)
        {
            blip1.SetActive(false);
            blip2.SetActive(true);
            blip3.SetActive(true);
            blip4.SetActive(true);
            blip5.SetActive(true);
            ShowSpeech("Our team will have the wrong location information.", 56, 275f);
        }
        else if (Step == 10)
        {
            blip2.SetActive(false);
            blip3.SetActive(false);
            blip4.SetActive(false);
            blip5.SetActive(false);
            book.gameObject.SetActive(true);
            ShowSpeech("To help you fulfill your task,  we have collected the best data on how to spot an AI spy in this book.", 56f, 330f);
        }
        else if (Step == 11)
        {
            audioSource.PlayOneShot(gruntSmall);
            book.anchoredPosition = new Vector2(334f, -1040);
            book.localScale = new Vector3(2.5f, 2.5f, 1f);
            ShowSpeech("Are you ready?", 56f, 165f);
        }
        else if (Step == 12)
        {
            SceneManager.LoadScene(1);
        }

    }

}
